### ISSUE TITLE
[Minor] v0.6.0 - Awkward delay when using knife

### ISSUE THREAD

**Issue by Exanite** [7ark/Rift#3]
There is a short delay before using the knife where the player does absolutely nothing.
This makes the knife really unsatisfying to use because you give up the safety of distance when you go in with melee. The half a second wait to actually kill them is usually enough time for the enemy to hit you or even kill you.

Edit: It is less awkward to use in slow mode, but the point stands.

**Comment by 7ark** [comment]
I'll take a look at speeding up the animation. The art will be changed in the future anyway, so that may change with time.
